name: ft_printf_test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global pull.rebase false
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Setup and tests
        run: |
          sudo apt-get update && sudo apt-get install make git clang valgrind -y
          make -C libft
          sed -i 's/-lftprintf/-lftprintf -L..\/libft -lft/g' printfTester/Makefile
          sed -i 's/tput setaf [0-9]* &&//g' printfTester/Makefile
          sed -i 's/tput setaf [0-9]*//g' printfTester/Makefile
          sed -i 's/@git pull/#@git pull/g' printfTester/Makefile
          make a -C printfTester
